name: Update Market Prices

on:
  schedule:
    # Roda a cada 10 minutos
    - cron: '*/10 * * * *'

  # Permite que você rode manualmente pelo GitHub (para testar)
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar a API de atualização do mercado (POST)
        run: |
          curl --request POST \
            --url 'https://www.mflprotocol.xyz/api/cron/refresh-market' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' \
            --fail
